config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Non production routes
  if Rails.env == "development"
    resources :emails, :only => [ :index ]
  end

  mount CatarsePaypalExpress::Engine => "/", :as => "catarse_paypal_express"
  mount CatarseMoip::Engine => "/", :as => "catarse_moip"

  filter :locale, exclude: /\/auth\//

  root to: 'projects#index'

  # Static Pages
  match '/sitemap' => "static#sitemap", :as => :sitemap
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/guidelines_tips" => "static#guidelines_tips", :as => :guidelines_tips
  match "/guidelines_backers" => "static#guidelines_backers", :as => :guidelines_backers
  match "/guidelines_start" => "static#guidelines_start", :as => :guidelines_start
  match "/about" => "static#about", :as => :about
  match "/faq" => "static#faq", :as => :faq

  match "/explore" => "explore#index", :as => :explore
  match "/explore#:quick" => "explore#index", :as => :explore_quick
  match "/credits" => "credits#index", :as => :credits

  match "/reward/:id" => "rewards#show", :as => :reward
  resources :posts, only: [:index, :create]

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy ]
    resources :backers, controller: 'projects/backers', only: [ :index, :show, :new, :create ] do
      member do
        match 'credits_checkout'
        post 'update_info'
      end
    end
    collection do
      get 'vimeo'
      get 'check_slug'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, :only => [:index]
    resources :unsubscribes, :only => [:create]
    collection do
      get 'set_email'
    end
    member do
      get 'projects'
      get 'credits'
      put 'unsubscribe_update'
      put 'update_email'
    end
  end
  match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  namespace :adm do
    resources :projects, only: [ :index, :update ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'unconfirm'
        put 'change_reward'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  match "/:permalink" => "projects#show", as: :project_by_slug
end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :omniauthable
  begin
    sync_with_mailchimp
  rescue Exception => e
    Airbrake.notify({ :error_class => "MailChimp Error", :error_message => "MailChimp Error: #{e.inspect}", :parameters => params}) rescue nil
    Rails.logger.info "-----> #{e.inspect}"
  end

  delegate  :display_name, :display_image, :short_name, :display_provider, :display_image_html,
    :medium_name, :display_credits, :display_total_of_backs,
    :to => :decorator

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,
    :password,
    :password_confirmation,
    :remember_me,
    :name,
    :nickname,
    :image_url,
    :uploaded_image,
    :bio,
    :newsletter,
    :full_name,
    :address_street,
    :address_number,
    :address_complement,
    :address_neighbourhood,
    :address_city,
    :address_state,
    :address_zip_code,
    :phone_number,
    :cpf,
    :state_inscription,
    :locale,
    :twitter,
    :facebook_link,
    :other_link,
    :moip_login

  include ActionView::Helpers::NumberHelper
  include ActionView::Helpers::TextHelper
  include Rails.application.routes.url_helpers

  mount_uploader :uploaded_image, LogoUploader

  validates_uniqueness_of :uid, :scope => :provider
  validates_length_of :bio, :maximum => 140
  validates :email, :email => true, :allow_nil => true, :allow_blank => true
  #validates :name, :presence => true, :if => :is_devise?

  validates_presence_of     :email, :if => :is_devise?
  validates_uniqueness_of   :email, :scope => :provider, :if => :is_devise?
  validates_presence_of     :password, :if => :password_required?
  validates_confirmation_of :password, :if => :password_required?
  validates_length_of       :password, :within => 6..128, :allow_blank => true

  schema_associations
  has_many :oauth_providers, through: :authorizations
  has_many :backs, class_name: "Backer"
  has_one :user_total

  accepts_nested_attributes_for :unsubscribes, allow_destroy: true rescue puts "No association found for name 'unsubscribes'. Has it been defined yet?"
  scope :backers, :conditions => ["id IN (SELECT DISTINCT user_id FROM backers WHERE confirmed)"]
  scope :who_backed_project, ->(project_id){ where("id IN (SELECT user_id FROM backers WHERE confirmed AND project_id = ?)", project_id) }
  scope :subscribed_to_updates, where("id NOT IN (SELECT user_id FROM unsubscribes WHERE project_id IS NULL AND notification_type_id = (SELECT id from notification_types WHERE name = 'updates'))")
  scope :subscribed_to_project, ->(project_id){ who_backed_project(project_id).where("id NOT IN (SELECT user_id FROM unsubscribes WHERE project_id = ?)", project_id) }
  scope :by_email, ->(email){ where('email ~* ?', email) }
  scope :by_payer_email, ->(email){  where('EXISTS(SELECT true FROM backers JOIN payment_notifications ON backers.id = payment_notifications.backer_id WHERE backers.user_id = users.id AND payment_notifications.extra_data ~* ?)', email) }
  scope :by_name, ->(name){ where('name ~* ?', name) }
  scope :by_id, ->(id){ where('users.id = ?', id) }
  scope :by_key, ->(key){ where('EXISTS(SELECT true FROM backers WHERE backers.user_id = users.id AND backers.key ~* ?)', key) }
  scope :has_credits, joins(:user_total).where('user_totals.credits > 0')
  scope :order_by, ->(sort_field){ order(sort_field) }

  def self.backer_totals
    connection.select_one(
      self.scoped.
      joins(:user_total).
      select('count(DISTINCT user_id) as users, count(*) as backers, sum(user_totals.sum) as backed, sum(user_totals.credits) as credits').
      to_sql
    ).reduce({}){|memo,el| memo.merge({ el[0].to_sym => BigDecimal.new(el[1] || '0') }) }
  end

  def decorator
    @decorator ||= UserDecorator.new(self)
  end

  def have_address?
    address_street.present? and address_number.present? and address_city.present?
  end

  def admin?
    admin
  end

  def credits
    user_total ? user_total.credits : 0.0
  end

  def facebook_id
    auth = authorizations.joins(:oauth_provider).where("oauth_providers.name = 'facebook'").first
    auth.uid if auth
  end

  def to_param
    return "#{self.id}" unless self.display_name
    "#{self.id}-#{self.display_name.parameterize}"
  end

  def self.create_with_omniauth(auth)
    u = create! do |user|
      user.name = auth["info"]["name"]
      user.email = (auth["info"]["email"] rescue nil)
      user.email = (auth["extra"]["user_hash"]["email"] rescue nil) unless user.email
      user.nickname = auth["info"]["nickname"]
      user.bio = (auth["info"]["description"][0..139] rescue nil)
      user.locale = I18n.locale.to_s

      if auth["provider"] == "twitter"
        user.image_url = "https://api.twitter.com/1/users/profile_image?screen_name=#{auth['info']['nickname']}&size=original"
      end

      if auth["provider"] == "facebook"
        user.image_url = "https://graph.facebook.com/#{auth['uid']}/picture?type=large"
      end
    end
    provider = OauthProvider.where(name: auth['provider']).first
    u.authorizations.create! uid: auth['uid'], oauth_provider_id: provider.id if provider
    u
  end

  def recommended_project
    # It returns the project that have the biggest amount of backers
    # that contributed to the last project the user contributed that has common backers.
    backs.includes(:project).confirmed.order('confirmed_at DESC').each do |back|
      project = ActiveRecord::Base.connection.execute("SELECT count(*), project_id FROM backers b JOIN projects p ON b.project_id = p.id WHERE p.expires_at > current_timestamp AND p.id NOT IN (SELECT project_id FROM backers WHERE confirmed AND user_id = #{id}) AND b.user_id in (SELECT user_id FROM backers WHERE confirmed AND project_id = #{back.project.id.to_i}) GROUP BY 2 ORDER BY 1 DESC LIMIT 1")
      return Project.find(project[0]["project_id"]) unless project.count == 0
    end
    nil
  end

  def total_backs
    backs.confirmed.not_anonymous.count
  end

  def updates_subscription
    unsubscribes.updates_unsubscribe(nil)
  end

  def project_unsubscribes
    backed_projects.map do |p|
      unsubscribes.updates_unsubscribe(p.id)
    end
  end

  def backed_projects
    Project.backed_by(self.id)
  end

  def backs_text
    if total_backs == 2
      I18n.t('user.backs_text.two')
    elsif total_backs > 1
      I18n.t('user.backs_text.many', :total => (total_backs-1))
    else
      I18n.t('user.backs_text.one')
    end
  end

  def remember_me_hash
    Digest::MD5.new.update("#{self.provider}###{self.uid}").to_s
  end

  def as_json(options={})

    json_attributes = {}

    if not options or (options and not options[:anonymous])
      json_attributes.merge!({
        :id => id,
        :name => display_name,
        :short_name => short_name,
        :medium_name => medium_name,
        :image => display_image,
        :total_backs => total_backs,
        :backs_text => backs_text,
        :url => user_path(self),
        :city => address_city,
        :state => address_state
      })
    end

    if options and options[:can_manage]
      json_attributes.merge!({
        :email => email
      })
    end

    json_attributes

  end

  def is_devise?
    provider == 'devise'
  end

  def twitter_link
    "http://twitter.com/#{self.twitter}"
  end

  def fix_twitter_user
    self.twitter.gsub!(/@/, '') if self.twitter
  end

  # Returns a Gravatar URL associated with the email parameter, uses local avatar if available
  def gravatar_url
    return unless email
    "https://gravatar.com/avatar/#{Digest::MD5.new.update(email)}.jpg?default=#{::Configuration[:base_url]}/assets/user.png"
  end

  protected
  def password_required?
    provider == 'devise' && (!persisted? || !password.nil? || !password_confirmation.nil?)
  end
end

app/controllers/adm/users_controller.rb
class Adm::UsersController < Adm::BaseController
  inherit_resources
  menu I18n.t("adm.users.index.menu") => Rails.application.routes.url_helpers.adm_users_path
  before_filter :set_title
  before_filter :set_totals

  has_scope :by_id, :by_name, :by_email, :by_payer_email, :by_key, :has_credits, :has_credits_difference, :only => :index

  protected
  def set_totals
    totals = end_of_association_chain.backer_totals
    @total_users = totals[:users].to_i
    @total_backs = totals[:backs]
    @total_backed = totals[:backed]
    @total_credits = totals[:credits]
  end

  def set_title
    @title = t("adm.users.index.title")
  end

  def collection
    @users ||= end_of_association_chain.order_by(params[:order_by] || 'coalesce(user_totals.sum, 0) DESC').includes(:user_total).page(params[:page])
  end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  load_and_authorize_resource new: [ :set_email ], except: [ :projects ]
  inherit_resources
  actions :show, :update, :unsubscribe_update, :request_refund, :set_email, :update_email
  respond_to :json, :only => [:backs, :projects, :request_refund]

  def show
    show!{
      fb_admins_add(@user.facebook_id) if @user.facebook_id
      @title = "#{@user.display_name}"
      @credits = @user.backs.can_refund.all
      @subscribed_to_updates = @user.updates_subscription
      @unsubscribes = @user.project_unsubscribes
    }
  end

  def set_email
    @user = current_user
  end

  def update_email
    update! do |success,failure|
      success.html do
        flash[:notice] = t('users.current_user_fields.updated')
        redirect_to (session[:return_to] || user_path(@user, :anchor => 'settings'))
        session[:return_to] = nil
        return
      end
      failure.html{ return render :set_email }
    end
  end

  def update
    update! do
      flash[:notice] = t('users.current_user_fields.updated')
      return redirect_to user_path(@user, :anchor => 'settings')
    end
  end

  def projects
    @user = User.find(params[:id])
    @projects = @user.projects.includes(:user, :category, :project_total).order("updated_at DESC")
    @projects = @projects.visible unless @user == current_user
    @projects = @projects.page(params[:page]).per(10)
    render :json => @projects
  end

  def credits
    @user = User.find(params[:id])
    @credits = @user.backs.can_refund.order(:id).all
    render :json => @credits
  end

  def request_refund
    back = Backer.find(params[:back_id])
    begin
      if can? :request_refund, back
        refund = Credits::Refund.new(back, current_user)
        refund.make_request!
        status = refund.message
      end
    rescue Exception => e
      status = e.message
    end

    render :json => {:status => status, :credits => current_user.reload.display_credits}
  end
end

app/views/users/_back.html.slim
script type="text/template" id="user_backs_template"
  ul.collection_list

script type="text/template" id="empty_user_back_template"
  - if !can? :manage, @user
    p.empty= t('users.backs.no_backs', name: @user.display_name)
  - else
    p.empty= t('users.backs.no_backs_current_user_html', link: ::Configuration[:base_url])

script type="text/template" id="user_back_template"
  div class=(can?(:manage, @user) ? 'project_land' : 'small_project_land')
    | <% if(project['expired']) { %>
    .status_image
      a href="<%= project['url'] %>"
        |<% if(project['successful']) { %>
        = image_tag "successful.#{I18n.locale}.png"
        |<% } else if(project['waiting_confirmation']) { %>
        = image_tag "waiting_confirmation.#{I18n.locale}.png"
        |<% } else { %>
        = image_tag "not_successful.#{I18n.locale}.png"
        |<% } %>
    | <% } %>
    .cover
      p.black_box <%= project['category']['name'] %>
      img[src="<%= project['image'] %>" width="218px" height="175px"]
    .project_infos
      .title
        h4
          a href='<%= project["url"] %>'
            | <%= project['name'] %>
        p.author== "#{t('project_by')} <%= project['user']['name'] %>"
        p.headline <%= project['headline'] %>
      .status_bar
        .progress style="width: <%= project['display_progress'] %>%;"
      ul
        li
          |<% if(project['time_to_go']['time'] > 0){ %>
          h6 <%= project['time_to_go']['time'] %> <%= project['time_to_go']['unit'] %>
          p <%= project['remaining_text'] %>
          |<% } else { %>
          h6 <%= project['display_status_to_box'] %>
          p <%= project['display_expires_at'] %>
          |<% } %>
        li
          h6 <%= project['progress'] %>%
          p= t('projects.project.backed')
        li
          h6 <%= project['pledged'] %>
          p= t('projects.project.reached')
    - if can? :manage, @user
      div.back_info
        ul
          li.date
            h5 <%= confirmed_at %>
          |<% if(display_value) { %>
          li.value
            h5 <%= display_value %>
          |<% } %>
          |<% if(reward) { %>
          li.reward
            h5 <%= reward['display_with_label'] %>
            | <% description = (reward['description']).replace(/"/g,'&quot;') %>
            p(title="<%= description %>") <%= jQuery.trim(reward['description']).substring(0, 75).trim(this) + "..."%>
          |<% } %>
      .tell_about
        p= t('tell_about_this_back')
        ul
          li= link_to image_tag('catarse/facebook_black_icon.png'), "http://www.facebook.com/sharer.php?u=<%= encodeURIComponent(project['full_uri']) %>&t=#{t('share_my_backs')}<%= encodeURIComponent(project['name']) %>".html_safe, :target => '_blank'
          li= link_to image_tag('catarse/twitter_black_icon.png'), "http://twitter.com/share?text=#{t('share_my_backs')}<%= encodeURIComponent(project['name']) %>&url=<%= encodeURIComponent(project['full_uri']) %>".html_safe, :target => '_blank'
  .clearfix

app/views/users/_current_user_fields.html.slim
#my_avatar
  h1 = t('.local_avatar')
  ul
    li
      .bootstrap-form
        = semantic_form_for @user do |f|
          = f.inputs do
            p= f.input :uploaded_image, :as => :file, :label => t('.submit_text')
          = f.actions do
            .bootstrap-twitter
              p= f.action :submit, :button_html => {:value => t('.submit'), :class => 'btn', :id => 'image_upload_btn'}
    li
      #gravatar_hint.alert.alert-info
        = link_to 'http://gravatar.com/', :target => :_blank do
          = image_tag 'gravatar.png', :id => 'gravatar_logo'
        p= t('.gravatar_hint_html', :link => link_to('Gravatar', 'http://gravatar.com/', :target => :_blank))
        .clearfix

#my_data
  h1= t('.my_data')
  ul
    li
      .bootstrap-form
        = semantic_form_for @user, :html => {:method => :put}  do |f|
          .profile
            = f.input :id, :as => :string, :input_html => { :disabled =>  'disabled'}
            = f.input :full_name, :required => true, :as => :string
            = f.input :cpf, :as => :string, :input_html => {:autocomplete => 'off'}
            = f.input :state_inscription, :as => :string
            = f.input :name, :required => false, :as => :string
            = f.input :address_street, :as => :string
            = f.input :address_number, :as => :string
            = f.input :address_complement, :required => false, :as => :string
            = f.input :address_neighbourhood, :as => :string
            = f.input :address_zip_code, :as => :string, :input_html => {:autocomplete => 'off'}
            = f.input :address_city, :as => :string
            = f.input :address_state, :as => :select, :collection => State.array
          .socialmidia
            .div
              = f.label :twitter, t('.twitter')
              = f.text_field :twitter
            .div
              = f.label :facebook_link, t('.facebook_link')
              = f.text_field :facebook_link
            .div
              = f.label :other_link, t('.other_link')
              = f.text_field :other_link
            = f.input :moip_login, label: (t('activerecord.attributes.user.moip_login') + '  ' +  link_to(t('activerecord.attributes.user.moip_login_hint'), "http://suporte.catarse.me/knowledgebase/articles/153570-como-criar-uma-conta-no-moip")).html_safe
            = f.input :phone_number, :required => false, :as => :string
            = f.input :email, :as => :string
            = hidden_field_tag 'id', @user.id
            = check_box_tag 'newsletter', '1', @user.newsletter
            = label_tag 'newsletter', t('.newsletter')
            = f.input :bio, :as => :text, :input_html => { :rows => 5, :cols => 20, :maxlength => 240  }
          .bootstrap-twitter
            p= f.submit t('.update_social_info'), :class => 'btn', :id => "user_submit"
- if @user.is_devise?
  #change_password
    h1= t('.change_password')
    ul
      li
        .bootstrap-form
          = form_for(@user, :as => :user, :url => registration_path(:user), :html => { :method => :put, :class => 'skip_feed_event' }) do |f|
            span.hint= t('.current_password_hint').html_safe
            br
            .div
              = f.label :current_password
              = f.password_field :current_password, :class=>'empty'
            .div
              = f.label :password, t('passwords.edit.label_new_password')
              = f.password_field :password, :class=>'empty'
            .div
              = f.label :password_confirmation
              = f.password_field :password_confirmation, :class=>'empty'
            .bootstrap-twitter
              p= f.submit 'OK', :class => 'btn'

app/views/users/_project.html.slim
script type="text/template" id="user_projects_template"
  ul.collection_list

script type="text/template" id="empty_user_project_template"
  - if current_user != @user
    p.empty= t('users.projects.no_projects', name: @user.display_name)
  - else
    p.empty= t('users.projects.no_projects_current_user_html', link: link_to(t('users.projects.here'), guidelines_start_path)).html_safe

script type="text/template" id="user_project_template"
  .small_project_land
    | <% if(expired) { %>
    .status_image
      a href="<%= url %>"
        |<% if(successful) { %>
        = image_tag "successful.#{I18n.locale}.png"
        |<% } else if(waiting_confirmation || waiting_funds) { %>
        = image_tag "waiting_confirmation.#{I18n.locale}.png"
        |<% } else { %>
        = image_tag "not_successful.#{I18n.locale}.png"
        |<% } %>
    | <% } %>
    .cover
      p.black_box <%= category['name'] %>
      img[src="<%= image %>" width="218px" height="175px"]
    .project_infos
      .title
        h4
          a href='<%= url %>'
            | <%= name %>
        p.author== "#{t('project_by')} <%= user['name'] %>"
        p.headline <%= headline %>
      .status_bar
        .progress style="width: <%= display_progress %>%;"
      ul
        li
          |<% if(time_to_go['time'] > 0){ %>
          h6 <%= time_to_go['time'] %> <%= time_to_go['unit'] %>
          p <%= remaining_text %>
          |<% } else { %>
          h6 <%= display_status_to_box %>
          p <%= display_expires_at %>
          |<% } %>
        li
          h6 <%= progress %>%
          p= t('projects.project.backed')
        li
          h6 <%= pledged %>
          p= t('projects.project.reached')
    - if current_user == @user
      .tell_about
        p= t('tell_about_this_project')
        ul
          li= link_to image_tag('catarse/facebook_black_icon.png'), "http://www.facebook.com/sharer.php?u=<%= encodeURIComponent(full_uri) %>&t=#{t('share_my_projects')}<%= encodeURIComponent(name) %>".html_safe, :target => '_blank'
          li= link_to image_tag('catarse/twitter_black_icon.png'), "http://twitter.com/share?text=#{t('share_my_projects')}<%= encodeURIComponent(name) %>&url=<%= encodeURIComponent(full_uri) %>".html_safe, :target => '_blank'
      .actions
        .bootstrap-twitter
          a href="<%= url %>#edit" class="btn"
            = t('edit_project')

app/views/users/_unsubscribes.html.slim
#my_data
  ul
    = I18n.t('users.unsubscribes.title')
  ul
    li
      .bootstrap-form
      = semantic_form_for(@user, url: user_unsubscribes_path(user_id: @user.id), html:{ method: :post}) do |f|
        = f.inputs do
          = f.semantic_fields_for :unsubscribes, @subscribed_to_updates do |u|
            - u.object.created_at.nil? ? (checked = { checked: 'checked' }) : (checked = nil)
            #subscribed_check
              = u.input :subscribed, as: :boolean, input_html: checked, label: I18n.t('users.unsubscribes.updates')
          - if @unsubscribes
            = f.semantic_fields_for :unsubscribes, @unsubscribes do |u|
              = u.inputs do
                - u.object.created_at.nil? ? (checked = { checked: 'checked' }) : (checked = nil)
                .subscribed_projects
                  = u.input :subscribed, as: :boolean, input_html: checked, label: Project.find(u.object.project_id).name
                = u.input :project_id, as: :hidden
                = u.input :user_id, as: :hidden
                = u.input :notification_type_id, as: :hidden

        p= f.submit t('users.current_user_fields.update_social_info'), :class => 'btn', :id => "unsubscribe_submit"

app/views/users/set_email.html.slim
= content_for :title do 
  = t('.site_title')

#page_content
  .container
    .devise_content
      .title
        h1=t('.title')
      .bootstrap-form
        = semantic_form_for @user, url: update_email_user_path(@user), html: { method: :put }  do |f|
          = f.inputs do
            = f.input :email, as: :string
          = f.actions do
            .bootstrap-twitter
              = f.submit t('.submit'), class: 'btn', id: 'user_submit'
    .clearfix

app/views/users/show.html.slim
= content_for :meta_tags do
  -# Meta tags for facebook social graph
  meta property="og:title" content=@user.name
  meta property="og:url" content=="#{Configuration[:base_url]}#{user_path(@user)}"
  meta property="og:image" content==@user.display_image
  meta property="og:site_name" content=::Configuration[:company_name]
  meta property="og:description" content=@user.bio
  meta property="fb:admins" content="#{fb_admins}"

- content_for :js_templates do
  = render 'back'
  = render 'project'

.bootstrap-twitter
  #creditsModal.hide.modal
    .modal-header
      h3= t('.attention')
    .modal-body
    .modal-footer
      a href="javascript:void(0);" class="btn" data-dimiss="modal"
        | OK

#page_content
  .container
    #user_profile[data-user="#{@user.to_json}"]
      .section_header
        .profile_image
          = @user.display_image_html
        .profile_title
          h1.profile
              = @user.display_name
          h4.bio
              = @user.bio
      .user_social
        ul
          - if can? :manage, @user
            li.email
              = mail_to @user.email, @user.email, :target => '_blank'
          - if @user.facebook_link
            li.facebook
              = link_to t('.user_social.facebook'), @user.facebook_link, :target => '_blank'
          - if @user.twitter
            li.twitter
              = link_to t('.user_social.twitter'), @user.twitter_link, :target => '_blank'
          - if @user.other_link
            li.other
              = link_to @user.other_link, @user.other_link, :target => '_blank'

      .tab_container
        nav#user_profile_menu
          = link_to t('.tabs.backed_projects'), '#backs', :id => 'backed_projects_link', :class => 'selected'
          = link_to t('.tabs.created_projects'), '#projects', :id => 'created_projects_link'
          / = link_to t('.tabs.comments'), '#comments', :id => 'comments_link'
          - if can? :manage, @user
            = link_to t('.tabs.credits'), '#credits', :id => 'credits_link'
            = link_to t('.tabs.settings'), '#settings', :id => 'settings_link'
            = link_to t('.tabs.unsubscribes'), '#unsubscribes', :id => 'unsubscribes_link'
      .clearfix
      #user_profile_content
        #user_backed_projects.content
        #user_created_projects.content
        - if can? :manage, @user
          #user_unsubscribes.content.hide
            = render 'unsubscribes'
          #user_settings.content.hide
            = render 'current_user_fields'
          #user_credits.content.hide
            .current_credits
              p= t('credits.index.current_credits_html', :credits => @user.display_credits)

            .table_title
              p= I18n.t('credits.index.refunds_title')
            .table_content
              table.table.table-striped
                thead
                  th= t('credits.index.project')
                  th= t('credits.index.back_date')
                  th= t('credits.index.value')
                  th= t('credits.index.refund_expration_date')
                  th= t('credits.index.status')
                - @credits.each do |credit|
                  tr[id="back_#{credit.id}"]
                    td.project_name
                      = link_to credit.project.name, credit.project, :class => 'link_project'
                    td.date= I18n.l(credit.created_at.to_date)
                    td.value= credit.display_value
                    td.term= I18n.l(credit.refund_deadline.to_date)
                    td.status
                      - if credit.requested_refund
                        = t('credits.index.requested_refund')
                      - elsif credit.refunded
                        = t('credits.index.refunded')
                      - else
                        - if can? :request_refund, credit
                          = link_to t('credits.index.request_refund'), "#request_refund/#{credit.id}", :class => 'link_project'
            .bootstrap-alert
              .alert.alert-info
                = t('credits.index.important_html')
      #loading= image_tag "loading.gif"
    .clearfix